<a href="https://colab.research.google.com/github/jagadeesh01032005/SML/blob/main/2290__sml_assignment_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [29]:
data = pd.read_csv("/content/breast_cancer_survival.csv")
print(data)

     Age  Gender  Protein1  Protein2  Protein3  Protein4 Tumour_Stage  \
0     42  FEMALE  0.952560   2.15000  0.007972 -0.048340           II
1     54  FEMALE  0.000000   1.38020 -0.498030 -0.507320           II
2     63  FEMALE -0.523030   1.76400 -0.370190  0.010815           II
3     78  FEMALE -0.876180   0.12943 -0.370380  0.132190            I
4     42  FEMALE  0.226110   1.74910 -0.543970 -0.390210           II
..   ...     ...       ...       ...       ...       ...          ...
329   59  FEMALE  0.024598   1.40050  0.024751  0.280320           II
330   41  FEMALE  0.100120  -0.46547  0.472370 -0.523870            I
331   54  FEMALE  0.753820   1.64250 -0.332850  0.857860           II
332   74  FEMALE  0.972510   1.42680 -0.366570 -0.107820           II
333   66  FEMALE  0.286380   1.39980  0.318830  0.836050           II

                          Histology ER status PR status HER2 status  \
0     Infiltrating Ductal Carcinoma  Positive  Positive    Negative
1     Infiltrating Ductal Carcinoma  Positive  Positive    Negative
2     Infiltrating Ductal Carcinoma  Positive  Positive    Negative
3     Infiltrating Ductal Carcinoma  Positive  Positive    Negative
4     Infiltrating Ductal Carcinoma  Positive  Positive    Positive
..                              ...       ...       ...         ...
329   Infiltrating Ductal Carcinoma  Positive  Positive    Positive
330   Infiltrating Ductal Carcinoma  Positive  Positive    Positive
331   Infiltrating Ductal Carcinoma  Positive  Positive    Negative
332  Infiltrating Lobular Carcinoma  Positive  Positive    Negative
333   Infiltrating Ductal Carcinoma  Positive  Positive    Negative

                    Surgery_type Date_of_Surgery Date_of_Last_Visit  \
0                          Other       20-May-18          26-Aug-18
1                          Other       26-Apr-18          25-Jan-19
2                     Lumpectomy       24-Aug-18          08-Apr-20
3                          Other       16-Nov-18          28-Jul-20
4                     Lumpectomy       12-Dec-18          05-Jan-19
..                           ...             ...                ...
329                   Lumpectomy       15-Jan-19          27-Mar-20
330  Modified Radical Mastectomy       25-Jul-18          23-Apr-19
331            Simple Mastectomy       26-Mar-19          11-Oct-19
332                   Lumpectomy       26-Nov-18          05-Dec-18
333  Modified Radical Mastectomy       04-Feb-19          10-Aug-19

    Patient_Status
0            Alive
1             Dead
2            Alive
3            Alive
4            Alive
..             ...
329          Alive
330          Alive
331           Dead
332          Alive
333           Dead

[334 rows x 15 columns]

In [30]:
from sklearn.preprocessing import LabelEncoder

In [31]:
for col in data.columns:
    if data[col].dtype == 'object':
        le = LabelEncoder()
        data[col] = le.fit_transform(data[col])

In [32]:
data

,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
0,42,0,0.952560,2.15000,0.007972,-0.048340,1,0,0,0,0,2,118,238,0
1,54,0,0.000000,1.38020,-0.498030,-0.507320,1,0,0,0,0,2,155,228,1
2,63,0,-0.523030,1.76400,-0.370190,0.010815,1,0,0,0,0,0,137,62,0
3,78,0,-0.876180,0.12943,-0.370380,0.132190,0,0,0,0,0,2,101,270,0
4,42,0,0.226110,1.74910,-0.543970,-0.390210,1,0,0,0,1,0,66,37,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,59,0,0.024598,1.40050,0.024751,0.280320,1,0,0,0,1,0,88,260,0
330,41,0,0.100120,-0.46547,0.472370,-0.523870,0,0,0,0,1,1,149,201,0
331,54,0,0.753820,1.64250,-0.332850,0.857860,1,0,0,0,0,3,159,103,1
332,74,0,0.972510,1.42680,-0.366570,-0.107820,1,1,0,0,0,0,162,34,0
333,66,0,0.286380,1.39980,0.318830,0.836050,1,0,0,0,0,1,20,85,1

In [33]:
x=data.drop('Patient_Status',axis=1)
print(x)
y=data['Patient_Status']

     Age  Gender  Protein1  Protein2  Protein3  Protein4  Tumour_Stage  \
0     42       0  0.952560   2.15000  0.007972 -0.048340             1
1     54       0  0.000000   1.38020 -0.498030 -0.507320             1
2     63       0 -0.523030   1.76400 -0.370190  0.010815             1
3     78       0 -0.876180   0.12943 -0.370380  0.132190             0
4     42       0  0.226110   1.74910 -0.543970 -0.390210             1
..   ...     ...       ...       ...       ...       ...           ...
329   59       0  0.024598   1.40050  0.024751  0.280320             1
330   41       0  0.100120  -0.46547  0.472370 -0.523870             0
331   54       0  0.753820   1.64250 -0.332850  0.857860             1
332   74       0  0.972510   1.42680 -0.366570 -0.107820             1
333   66       0  0.286380   1.39980  0.318830  0.836050             1

     Histology  ER status  PR status  HER2 status  Surgery_type  \
0            0          0          0            0             2
1            0          0          0            0             2
2            0          0          0            0             0
3            0          0          0            0             2
4            0          0          0            1             0
..         ...        ...        ...          ...           ...
329          0          0          0            1             0
330          0          0          0            1             1
331          0          0          0            0             3
332          1          0          0            0             0
333          0          0          0            0             1

     Date_of_Surgery  Date_of_Last_Visit
0                118                 238
1                155                 228
2                137                  62
3                101                 270
4                 66                  37
..               ...                 ...
329               88                 260
330              149                 201
331              159                 103
332              162                  34
333               20                  85

[334 rows x 14 columns]

In [34]:
x
y

0      0
1      1
2      0
3      0
4      0
      ..
329    0
330    0
331    1
332    0
333    1
Name: Patient_Status, Length: 334, dtype: int64

In [39]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [40]:
# Train SVM, KNN, and Logistic Regression and calculate accuracy
def train_and_evaluate(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    return accuracy

In [41]:
# Define the models
models = {
    "SVM": SVC(),
    "KNN": KNeighborsClassifier(),
    "Logistic Regression": LogisticRegression()
}

In [42]:
# Train and evaluate each model before PCA
print("Accuracy before PCA:")
for name, model in models.items():
    accuracy = train_and_evaluate(model, X_train, X_test, y_train, y_test)
    print(f"{name}: {accuracy:.2f}")

Accuracy before PCA:
SVM: 0.78
KNN: 0.76
Logistic Regression: 0.76

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [43]:
# Reduce dimensions with PCA
pca = PCA(n_components=0.95)  # retain 95% of variance
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

In [44]:
# Train and evaluate each model after PCA
print("\nAccuracy after PCA:")
for name, model in models.items():
    accuracy = train_and_evaluate(model, X_train_pca, X_test_pca, y_train, y_test)
    print(f"{name}: {accuracy:.2f}")

Accuracy after PCA:
SVM: 0.78
KNN: 0.75
Logistic Regression: 0.82